version: '3.8'

services:
  mining_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: your_username/mining_service:latest
    container_name: mining_service
    deploy:
      replicas: 3  # Số lượng bản sao để hỗ trợ khả năng mở rộng
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      # Các biến môi trường cần thiết
      DEBIAN_FRONTEND: noninteractive
      PYTHONDONTWRITEBYTECODE: '1'
      PYTHONUNBUFFERED: '1'
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      LOG_ENCRYPTION_KEY: ${LOG_ENCRYPTION_KEY}
      SCRIPT_DIR: /app/mining_environment/scripts
      CONFIG_DIR: /app/mining_environment/config
      MODELS_DIR: /app/mining_environment/models
      LOGS_DIR: /app/mining_environment/logs
      RESOURCES_DIR: /app/mining_environment/resources
      MINING_COMMAND: /usr/local/bin/mlinference
      MINING_CONFIG: mlinference_config.json
    volumes:
      - mining_data:/app/mining_environment/data
      - mining_logs:/app/mining_environment/logs
      - ./stunnel.conf:/etc/stunnel/stunnel.conf:ro  # Chỉ đọc để bảo mật
      # Thêm các volume khác nếu cần
    networks:
      - mining_network
    ports:
      - "8000:8000"  # Chuyển tiếp cổng nếu ứng dụng của bạn sử dụng cổng này
    restart: unless-stopped
    runtime: nvidia  # Đảm bảo sử dụng runtime NVIDIA
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Các dịch vụ bổ sung có thể được thêm ở đây, ví dụ:
  # database:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mining_db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - mining_network

networks:
  mining_network:
    driver: bridge

volumes:
  mining_data:
    driver: local
  mining_logs:
    driver: local
  # db_data:
  #   driver: local

