name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Lấy mã nguồn từ repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Thiết lập môi trường Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # Thay đổi phiên bản Python nếu cần

    # Cài đặt các phụ thuộc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt  # Đường dẫn đến requirements.txt trong thư mục app

    # Chạy kiểm thử
    - name: Run tests
      run: |
        pytest app/tests  # Đường dẫn đến thư mục kiểm thử trong thư mục app
