name: Python CI

on:
  push:
    branches:
      - main  # Chạy kiểm thử khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Chạy kiểm thử khi có pull request vào nhánh main

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu mới nhất

    steps:
    # Lấy mã nguồn từ repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Thiết lập môi trường Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Bạn có thể thay đổi phiên bản Python nếu cần

    # Cài đặt các dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Cài các thư viện từ requirements.txt

    # Chạy kiểm thử với pytest (hoặc unittest)
    - name: Run tests
      run: |
        pytest tests  # Thư mục tests chứa các bài kiểm thử của bạn
